name: trading_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cmake
  - pybind11
  - gcc_linux-64
  - gxx_linux-64
  - make
  - doxygen
  - numpy
  - pandas
  - matplotlib
  - gymnasium
  - pip
  - pip:
    - stable-baselines3
    - shimmy
